config/routes.rb
Rails.application.routes.draw do

  root 'events#index'
  devise_for :users
  get 'static_pages/index'
  get 'static_pages/secret'
get 'events/index'
resources :events
  get 'user',to: 'users#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/add_creators_to_event.rb
class AddCreatorsToEvent < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord

after_create :attendance_send
belongs_to :user
belongs_to :event

def attendance_send
AttendanceMailer.invitation_email(self.user, self.event.creator, self.event).deliver_now
end

end

app/models/event.rb
class Event < ApplicationRecord

has_many :attendances
has_many :users, through: :attendances
belongs_to :creator, class_name: "User" 

validates :start_date, presence: true
validate :is_start_date_past? #adef

validates :duration, presence: true
validate :is_duration_ok? #adef

validates :title, presence: true, length: {in: 5..140}

validates :description, presence: true, length: {in: 20..1000}

validates :price, presence: true, numericality: {greater_than: 0, less_than: 1001}

validates :location, presence: true 

def is_start_date_past?
 if start_date < Time.new
	errors.add(:start_date, "can't change a past event")
   end
end

def is_duration_ok?
 if (duration <= 0) || (duration % 5 != 0)
	errors.add(:duration, "duratino can't be negative and must be multiple of 5")
  end
end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

after_create :welcome_send

has_many :attendances
has_many :events, through: :attendances
has_many :creators, foreign_key: "creator_id", class_name: "Event"

def welcome_send
UserMailer.welcome_email(self).deliver_now
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :configure_devise_parameters, if: :devise_controller?

def configure_devise_parameters
 devise_parameter_sanitizer.permit(:sign_up) {|u| u.permit(:first_name, :last_name, :is_alive, :email, :password, :password_confirmation)}
 devise_parameter_sanitizer.permit(:account_update) {|u| u.permit(:first_name, :last_name, :is_alive, :email, :password, :password_confirmation)}
end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

def index
@events = Event.all
end

def new
end

def show
end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
before_action :authenticate_user!, only: [:ddsecret]
  def index
  end

  def secret
  end


end

app/controllers/user_controller.rb
class UserController < ApplicationController
def index
@users = User.all
end

def new
@user = User.new
end

def create
@user = User.new(params)
end

def show
@users = user
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Heroic Features - Start Bootstrap Template</title>

  <!-- Bootstrap core CSS -->
  <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="css/heroic-features.css" rel="stylesheet">

</head>

<body>

  <!-- Page Content -->
  <div class="container">

    <!-- Jumbotron Header -->
    <header class="jumbotron my-3">
      <h1 class="text-center display-3">My Zevents</h1>
      <h3 class="text-center">Retrouve toutes les actus sur les Zevents les plus chauds près de chez toi !</h3>
</header>
</div>
<% @events.each do |z| %>

<center>
<div class="col-lg-6 col-lg-6 mb-4">
        <div class="card h-100">
          <div class="card-body">
            <h4 class="card-title"><%=z.title%></h4>
            <p class="card-text"><%=z.description%></p>
          </div>
  <a href="#" class="btn btn-lg btn-outline-secondary">Date : <%=z.start_date%></a>

          <div class="card-footer">

            <a href="#" class="btn btn-lg btn-success">Lieu: <%=z.location%></a>
            <a href="#" class="btn btn-lg btn-danger">Intéressé par cet event ?</a>
<div class="btn btn-lg btn-light"><%=z.price%> €</div>
          </div>
        </div>
</div>

<%end%>
</center>
  <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

</body>


</html>

app/views/events/new.html.erb
<div class="row">
	<div class="col-md-10 col-lg-5 mx-auto">
		<div class= "h4 text-center">
			<center>
				<br>
				<h1>Crée ton évenement : </h1>
				<br/>
				<%= form_tag url_for(action: 'create'), method: "post" do %>
				<%= label_tag "Nom de l'évenement :" %>
				<div class="form-label-group">
					<%= text_field_tag 'title', value = nil, options = {style:"height:40px;width:500px",class: "form-control"} %>
				</div>
				<%= label_tag "Date (YYYY-MM-DD) : " %>
				<div class="form-label-group">
					<%= text_field_tag 'start_date', value = nil, options = {style:"height:40px;width:500px",class: "form-control"} %>
				</div>
				<%= label_tag "Durée(en minutes !):" %>
				<div class="form-label-group">
					<%= text_field_tag 'duration', value = nil, options = {style:"height:40px;width:500px",class: "form-control"} %>
				</div>
				<%= label_tag "Description :"  %>
				<div class="form-label-group">
					<%= text_field_tag 'description', value = nil, options = {style:"height:40px;width:500px",class: "form-control"} %>
				</div>
				<%= label_tag "Prix :" %>
				<div class="form-label-group">
					<%= text_field_tag 'price', value = nil, options = {style:"height:40px;width:500px",class: "form-control"} %>
				</div>
				<%= label_tag "Lieu :" %>
				<div class="form-label-group">
					<%= text_field_tag 'location', value = nil, options = {style:"height:40px;width:500px",class: "form-control"} %>
				</div>
				<br>
				<%= submit_tag "Créer mon Event", class: 'btn btn-lg btn-danger btn-block font-weight-bold'  %>
				<% end %>
			</center>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
<title>Les Zevents</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</head>
<body>

<nav class="navbar navbar-expand-sm bg-info navbar-dark">
  <!-- Brand -->
  <a class="navbar-brand" href="/events/index"><h3>Zevents</h3></a>

  <ul class="navbar-nav">
   
    <!-- Dropdown si user déco-->
<% if !user_signed_in? %>
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
        S'inscrire/Se Connecter
      </a>
      <div class="dropdown-menu">
        <a class="dropdown-item" href="/users/sign_up">S'inscrire</a>
        <a class="dropdown-item" href="/users/sign_in">Se Connecter</a>
      </div>
    </li>
<!--Si user co -->
<%else%>
 <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
        Mon Profil
      </a>
      <div class="dropdown-menu">
        <a class="dropdown-item" href="/">Mon profil</a>
        <a class="dropdown-item" href="#">Se déconnecter</a>
      </div>
    </li>
  </ul>
<%end%>
  <!-- Links -->
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" href="/events/new">MyZevents</a>
    </li>
</nav>
  </head>

  <body>
    <%=yield %>
  </body>
</html>

app/views/static_pages/index.html.erb
<%#sico%>
<ul>
  <% if user_signed_in? %>
<br><br><br>
<center>
<h1>Bienvenue dans ton espace privé n° <%=current_user.id%></h1><br>
<br>
   <center> <h3 class= "mb-3">  Voici ton email :<%= current_user.email %></h3></center>
<br><br>
<%= link_to "Edit email / password", edit_user_registration_path,class: " btn btn-lg btn-outline-secondary"%> 
<br><br>
  <%= link_to "Secret page", static_pages_secret_path, class: "btn btn-lg btn-outline-warning"%>
<br><br>
</center>
  <%= link_to "Sign out", destroy_user_session_path, class:"btn btn-lg btn-info", method: :delete %>

<%#si deco%>
  <% else %>
<div style= "margin: 280px">
<center>
<h1>Vous avez déjà un compte ? Identifez-vous</h1><br>

 <%#= link_to "Sign in", new_user_session_path %>

<a href = "/users/sign_in" class ="btn btn-info btn-lg btn-block">Sign in</button></a>
<br><br>
<h1>Sinon, créez votre compte en un clic! </h1><br>

<%#= link_to "Sign up", new_user_registration_path %>

<a href = "/users/sign_up" class ="btn btn-info btn-lg btn-block">Sign up</button></a>
</center>

  <% end %>
</ul>
</div>

app/views/static_pages/secret.html.erb
<h1>StaticPages#secret</h1>
<p>Frind me in app/views/static_pages/secret.html.erb</p>

app/views/users/show.html.erb
  </div>
<h1>Profil de <%=@user.first_name%></h1>
  <div class="card-body">
    <h4 class="card-title"><strong><%= @user.first_name %> <%= @user.last_name%></strong></h4>
    <h6 class="card-text"><%= @user.description %></h6>
    <h6 class="card-text"><%= @user.email %></h6>
    <h6 class="card-text">Profil crée le <%= @user.created_at.strftime("%Y-%m-%d") %></h6><br>
  </div>
</div>
<br>